// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vieraskirja.Data;

#nullable disable

namespace vieraskirja.Migrations
{
    [DbContext(typeof(VieraskirjaContext))]
    [Migration("20220607191314_kolmas")]
    partial class kolmas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("vieraskirja.Data.Kirjoitus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Kirjoittaja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PVM")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Viesti")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kirjoitukset");
                });
#pragma warning restore 612, 618
        }
    }
}
